# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_FCCMP_IOCTL)	+= fccmp_ioctl.o
obj-$(CONFIG_FCCMP_SYSCALL)	+= fccmp_syscall.o
obj-$(CONFIG_FCCMP_ARRAY)	+= fccmp_array.o
obj-$(CONFIG_FCCMP_NT)		+= fccmp_nt.o
obj-$(CONFIG_FCCMP_NT)		+= fccmp_avx.o
obj-$(CONFIG_FCCMP_EVENT)	+= fccmp_event.o
obj-$(CONFIG_SYSCALL_BENCH)	+= syscall_bench.o
