# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_FASTCALL_EXAMPLES)		+= fastcall_examples.o
fastcall_examples-y			+= fastcall_driver.o
fastcall_examples-$(CONFIG_X86_64)	+= functions_x86_64.o
fastcall_examples-$(CONFIG_ARM64)	+= functions_arm64.o
